---

on:  # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'infection.json'
      - 'composer.*'
      - '.github/workflows/mutation.yml'
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'infection.json'
      - 'composer.*'
      - '.github/workflows/mutation.yml'

name: 🧬 Mutation testing

jobs:
  infection:
    timeout-minutes: 6
    runs-on: ${{ matrix.os }}
    env:
      COMPOSER_ROOT_VERSION: '1.x-dev'
    concurrency:
      cancel-in-progress: true
      group: infection-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        php-version:
          - '8.4'
        dependencies:
          - highest
    steps:
      - name: 📦 Check out the codebase
        uses: actions/checkout@v6

      - name: 🛠️ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          ini-values: error_reporting=E_ALL
          coverage: xdebug

      - name: 🤖 Validate composer.json
        run: composer validate --ansi --strict

      - name: 📥 Install dependencies with composer
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: 🧬 Run mutation testing using infection/infection
        run: composer infection:ci
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ github.event_name == 'push' && secrets.STRYKER_DASHBOARD_API_KEY || '' }}
